# Generated by Django 5.1.7 on 2025-12-08 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('boss_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boss_name', models.CharField(max_length=100)),
                ('boss_image', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('profile_img', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Done', 'Done')], default='Working', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='api.businessuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBoss',
            fields=[
                ('project_boss_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hp', models.IntegerField(default=1000)),
                ('status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead')], default='Alive', max_length=10)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.boss')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bosses', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='BossAttack',
            fields=[
                ('boss_attack_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('damage_point', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project_boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='api.projectboss')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('project_member_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hp', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead')], default='Alive', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.businessuser')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=0)),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('InProgress', 'In Progress'), ('Finish', 'Finish')], default='Todo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.task')),
            ],
        ),
        migrations.CreateModel(
            name='UserAttack',
            fields=[
                ('user_attack_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('damage_point', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='api.projectmember')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('Boss', 'Boss'), ('User', 'User')], max_length=10)),
                ('boss_attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bossattack')),
                ('project_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.projectmember')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.task')),
                ('user_attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userattack')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.businessuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to='api.businessuser')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to='api.report')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reports', to='api.businessuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='api.achievement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='api.businessuser')),
            ],
            options={
                'unique_together': {('user', 'achievement', 'project')},
            },
        ),
        migrations.CreateModel(
            name='UserBossCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defeat_at', models.DateTimeField(auto_now_add=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to='api.boss')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_boss_collections', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss_collections', to='api.businessuser')),
            ],
            options={
                'unique_together': {('user', 'boss', 'project')},
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.projectmember')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_members', to='api.task')),
            ],
            options={
                'unique_together': {('project_member', 'task')},
            },
        ),
    ]
