# Generated by Django 5.1.7 on 2026-01-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_type_project_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
    ]
