# Generated by Django 5.1.7 on 2026-01-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('Todo', 'Todo'), ('InProgress', 'In Progress'), ('Finish', 'Finish')], default='Todo', max_length=20),
        ),
    ]
