# Generated by Django 5.1.7 on 2026-01-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'backlog'), ('todo', 'todo'), ('inProgress', 'in Progress'), ('done', 'done')], default='Todo', max_length=20),
        ),
    ]
