# Generated by Django 5.1.7 on 2026-01-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboss',
            name='max_hp',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='projectboss',
            name='hp',
            field=models.IntegerField(default=0),
        ),
    ]
