# Generated by Django 5.1.7 on 2026-01-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_projectboss_max_hp_alter_projectboss_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='max_hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='hp',
            field=models.IntegerField(default=0),
        ),
    ]
