# Generated by Django 5.1.7 on 2026-01-18 15:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_projectmember_max_hp_alter_projectmember_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='action',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='action_type',
            field=models.CharField(choices=[('USER', 'User'), ('BOSS', 'Boss'), ('SYSTEM', 'System')], default='SYSTEM', max_length=10),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklog',
            name='event',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('TASK_COMPLETED', 'Task Completed'), ('USER_ATTACK', 'User Attack'), ('BOSS_ATTACK', 'Boss Attack'), ('APPLY_BUFF', 'Apply Buff'), ('APPLY_DEBUFF', 'Apply Debuff'), ('GIVE_ITEM', 'Give Item'), ('BUFF_APPLIED', 'Buff Applied'), ('DEBUFF_APPLIED', 'Debuff Applied'), ('RECIEVE_ITEM', 'Recieve Item'), ('USE_ITEM', 'Use Iten')], default='TASK_CREATED', max_length=50),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='project_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.projectmember'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.task'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.projectmember'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to='api.projectmember'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reports', to='api.projectmember'),
        ),
    ]
