# Generated by Django 5.1.7 on 2026-01-18 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_tasklog_action_tasklog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.project'),
        ),
    ]
