# Generated by Django 5.1.7 on 2026-01-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tasklog_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='project',
        ),
    ]
