# Generated by Django 5.1.7 on 2026-01-18 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_tasklog_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboss',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectboss',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
