# Generated by Django 5.1.7 on 2026-01-18 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_projectboss_created_at_projectboss_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboss',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
