# Generated by Django 5.1.7 on 2026-01-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_projectboss_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='event',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('TASK_COMPLETED', 'Task Completed'), ('ASSIGN_USER', 'Assign User'), ('UNASSIGN_USER', 'Unassign User'), ('USER_ATTACK', 'User Attack'), ('BOSS_ATTACK', 'Boss Attack'), ('APPLY_BUFF', 'Apply Buff'), ('APPLY_DEBUFF', 'Apply Debuff'), ('GIVE_ITEM', 'Give Item'), ('BUFF_APPLIED', 'Buff Applied'), ('DEBUFF_APPLIED', 'Debuff Applied'), ('RECIEVE_ITEM', 'Recieve Item'), ('USE_ITEM', 'Use Iten')], default='TASK_CREATED', max_length=50),
        ),
    ]
