# Generated by Django 5.1.7 on 2026-01-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_tasklog_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboss',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.boss'),
        ),
    ]
