# Generated by Django 5.1.7 on 2026-01-21 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_projectboss_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('effect_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effect_type', models.CharField(choices=[('DAMAGE_BUFF', 'Damage Buff'), ('DAMAGE_DEBUFF', 'Damage Debuff'), ('SCORE_BONUS', 'Score Bonus'), ('SCORE_PENALTY', 'Score Penalty'), ('DEFENCE_BUFF', 'Defence Buff'), ('DEFENCE_DEBUFF', 'Defence Debuff'), ('HEAL', 'Heal')], max_length=50)),
                ('value', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='boss_attack',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='user_attack',
        ),
        migrations.AddField(
            model_name='bossattack',
            name='project_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boss_attacks', to='api.projectmember'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='damage_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='project_boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.projectboss'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='recieved_project_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_logs', to='api.projectmember'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='score_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userattack',
            name='project_boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_attacks', to='api.projectboss'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='event',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('TASK_COMPLETED', 'Task Completed'), ('ASSIGN_USER', 'Assign User'), ('UNASSIGN_USER', 'Unassign User'), ('USER_ATTACK', 'User Attack'), ('BOSS_ATTACK', 'Boss Attack'), ('APPLY_BUFF', 'Apply Buff'), ('APPLY_DEBUFF', 'Apply Debuff'), ('GIVE_ITEM', 'Give Item'), ('USE_ITEM', 'Use Item'), ('HEAL', 'Heal')], default='TASK_CREATED', max_length=50),
        ),
        migrations.CreateModel(
            name='UserEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.effect')),
                ('project_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projectmember')),
            ],
        ),
    ]
