# Generated by Django 5.1.7 on 2026-01-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_effect_remove_tasklog_boss_attack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='boss_image',
            field=models.CharField(max_length=255),
        ),
    ]
