# Generated by Django 5.1.7 on 2026-01-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_boss_boss_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='boss_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Special', 'Special')], default='Normal', max_length=50),
        ),
        migrations.AddField(
            model_name='projectboss',
            name='phrase',
            field=models.IntegerField(default=1),
        ),
    ]
