# Generated by Django 5.1.7 on 2026-01-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_tasklog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='Task_priority_snapshot',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
