# Generated by Django 5.1.7 on 2026-01-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='Task_priority_snapshot',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task_priority_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
