# Generated by Django 5.1.7 on 2026-01-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_tasklog_task_priority_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='event',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('TASK_COMPLETED', 'Task Completed'), ('ASSIGN_USER', 'Assign User'), ('UNASSIGN_USER', 'Unassign User'), ('USER_ATTACK', 'User Attack'), ('BOSS_ATTACK', 'Boss Attack'), ('APPLY_BUFF', 'Apply Buff'), ('APPLY_DEBUFF', 'Apply Debuff'), ('GIVE_ITEM', 'Give Item'), ('USE_ITEM', 'Use Item'), ('HEAL', 'Heal'), ('KILL_BOSS', 'Kill Boss'), ('KILL_PLAYER', 'Kill Player')], default='TASK_CREATED', max_length=50),
        ),
    ]
