# Generated by Django 5.1.7 on 2026-02-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_tasklog_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectboss',
            old_name='phrase',
            new_name='phase',
        ),
    ]
