# Generated by Django 5.1.7 on 2026-02-06 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_tasklog_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklog',
            old_name='recieved_project_member',
            new_name='received_project_member',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_name',
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='api.projectmember'),
        ),
        migrations.AddField(
            model_name='report',
            name='sentiment_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='api.task'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='event',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_REVIEW', 'Task Review'), ('ASSIGN_USER', 'Assign User'), ('UNASSIGN_USER', 'Unassign User'), ('USER_ATTACK', 'User Attack'), ('BOSS_ATTACK', 'Boss Attack'), ('APPLY_BUFF', 'Apply Buff'), ('APPLY_DEBUFF', 'Apply Debuff'), ('GIVE_ITEM', 'Give Item'), ('USE_ITEM', 'Use Item'), ('HEAL', 'Heal'), ('KILL_BOSS', 'Kill Boss'), ('KILL_PLAYER', 'Kill Player')], default='TASK_CREATED', max_length=50),
        ),
    ]
