# Generated by Django 5.1.7 on 2026-01-31 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_tasklog_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInviteToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expired_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='api.project')),
            ],
            options={
                'db_table': 'project_invite_tokens',
                'indexes': [models.Index(fields=['project', 'email'], name='project_inv_project_7346da_idx'), models.Index(fields=['token'], name='project_inv_token_5e27b1_idx'), models.Index(fields=['expired_at'], name='project_inv_expired_a51f75_idx')],
            },
        ),
    ]
