# Generated by Django 5.1.7 on 2026-02-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_recieved_project_member_tasklog_received_project_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='rare_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
