# Generated by Django 5.1.7 on 2026-02-07 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_phrase_projectboss_phase_effect_rare_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='effect_polarity',
            field=models.CharField(choices=[('DAMAGE_BUFF', 'Damage Buff'), ('DAMAGE_DEBUFF', 'Damage Debuff'), ('SCORE_BONUS', 'Score Bonus'), ('SCORE_PENALTY', 'Score Penalty'), ('DEFENCE_BUFF', 'Defence Buff'), ('DEFENCE_DEBUFF', 'Defence Debuff'), ('HEAL', 'Heal')], default='GOOD', max_length=50),
        ),
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('status_effect_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('BUFF', 'Buff'), ('DEBUFF', 'Debuff')], max_length=10)),
                ('duration_turns', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effects', models.ManyToManyField(related_name='status_effects', to='api.effect')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_effects', models.ManyToManyField(blank=True, related_name='items', to='api.statuseffect')),
            ],
        ),
    ]
