# Generated by Django 5.1.7 on 2026-02-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_phrase_projectboss_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='effect_polarity',
            field=models.CharField(choices=[('GOOD', 'Good'), ('BAD', 'Bad')], default='GOOD', max_length=50),
        ),
    ]
