# Generated by Django 5.1.7 on 2026-02-07 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_projectboss_phrase_projectboss_phase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status_effects',
        ),
        migrations.AddField(
            model_name='item',
            name='effects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='api.effect'),
        ),
        migrations.DeleteModel(
            name='StatusEffect',
        ),
    ]
