# Generated by Django 5.1.7 on 2026-02-08 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_item_status_effects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('user_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='api.item')),
                ('project_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.projectmember')),
            ],
        ),
    ]
