# Generated by Django 5.1.7 on 2026-02-08 16:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_phrase_projectboss_phase_useritem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useritem',
            old_name='obtained_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='usereffect',
            name='id',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='usereffect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usereffect',
            name='user_effect_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
