# Generated by Django 5.1.7 on 2026-02-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_projectinvitetoken'),
        ('api', '0024_rename_phrase_projectboss_phase'),
        ('api', '0030_rename_phrase_projectboss_phase_and_more'),
    ]

    operations = [
    ]
