# Generated by Django 5.1.7 on 2026-02-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20260215_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklog',
            old_name='log_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='damage_point',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='event',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='project_boss',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='project_member',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='received_project_member',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='report',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='score_change',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='task_priority_snapshot',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='actor_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='actor_type',
            field=models.CharField(choices=[('user', 'User'), ('boss', 'Boss'), ('system', 'System')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='event_type',
            field=models.CharField(blank=True, choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_REVIEW', 'Task Review'), ('ASSIGN_USER', 'Assign User'), ('UNASSIGN_USER', 'Unassign User'), ('USER_ATTACK', 'User Attack'), ('BOSS_ATTACK', 'Boss Attack'), ('HEAL', 'Heal'), ('APPLY_BUFF', 'Apply Buff'), ('APPLY_DEBUFF', 'Apply Debuff'), ('GIVE_ITEM', 'Give Item'), ('USE_ITEM', 'Use Item'), ('KILL_BOSS', 'Kill Boss'), ('KILL_PLAYER', 'Kill Player')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='project_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['project_id', 'created_at'], name='api_tasklog_project_b9ca68_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['project_id', 'event_type', 'created_at'], name='api_tasklog_project_72e371_idx'),
        ),
    ]
