# Generated by Django 5.1.7 on 2026-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_log_id_tasklog_id_remove_tasklog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='overall_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='strength',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='team_work',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='work_load_per_day',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='work_speed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='event_type',
            field=models.CharField(blank=True, choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_REVIEW', 'Task Review'), ('ASSIGN_USER', 'Assign User'), ('UNASSIGN_USER', 'Unassign User'), ('USER_ATTACK', 'User Attack'), ('BOSS_ATTACK', 'Boss Attack'), ('HEAL', 'Heal'), ('APPLY_BUFF', 'Apply Buff'), ('APPLY_DEBUFF', 'Apply Debuff'), ('GIVE_ITEM', 'Give Item'), ('USE_ITEM', 'Use Item'), ('KILL_BOSS', 'Kill Boss'), ('KILL_PLAYER', 'Kill Player'), ('USER_REVIVE', 'User Revive'), ('BOSS_REVIVE', 'Boss Revive'), ('BOSS_NEXT_PHASE_SETUP', 'Boss Next Phase Setup')], db_index=True, max_length=50, null=True),
        ),
    ]
