# Generated by Django 5.1.7 on 2026-03-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_userfeedback_overall_quality_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='role_assigned',
            field=models.TextField(blank=True, null=True),
        ),
    ]
