# Generated by Django 5.1.7 on 2026-03-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_userfeedback_role_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='diligence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
