# Generated by Django 5.1.7 on 2026-03-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_userfeedback_diligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline_decision',
            field=models.CharField(blank=True, choices=[('closed', 'Closed'), ('continued', 'Continued')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline_decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
