# Generated by Django 5.1.7 on 2026-03-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_project_deadline_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEndSummary',
            fields=[
                ('project_member_id', models.UUIDField(primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('damage_deal', models.IntegerField()),
                ('damage_receive', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('is_mvp', models.BooleanField(default=False)),
                ('boss', models.JSONField()),
                ('boss_count', models.IntegerField()),
                ('reduction_percent', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'boss_battle_member_snapshot',
                'indexes': [models.Index(fields=['project_id'], name='boss_battle_project_0ea765_idx'), models.Index(fields=['project_id', '-score'], name='boss_battle_project_29dc87_idx')],
            },
        ),
    ]
